In [ ]:
pip install selenium

### Preencher Formulários com Selenium

Link do formulário: https://forms.gle/fTG7MkjZqWaRgg2GA

In [41]:
from selenium import webdriver
from selenium.webdriver.common.by import By


navegador = webdriver.Chrome()
navegador.get("http://127.0.0.1:5500/templates/formulario.html")

In [42]:
# Preencher CPF
navegador.find_element(By.XPATH, '//*[@id="cpf"]').send_keys("11111111111")

# Preencher e-mail
navegador.find_element(By.XPATH, '//*[@id="email"]').send_keys("emailqualquer@gmail.com")

# Preencher descrição
navegador.find_element(By.XPATH, '//*[@id="descricao"]').send_keys("Teste de automação com Selenium.")

### Fazer a partir de uma planilha e várias vezes:

In [43]:
pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\noturno\anaconda3\envs\turma2\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\noturno\anaconda3\envs\turma2\lib\site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [44]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

df = pd.read_excel("2.Mechanical Sampling_v2 (P).xlsx")
display(tabela)

,Unnamed: 0,Não,padrão número (Rev.)Data de revisão,Item,Alto riscoAlvoSe,G-ERPteste Tipo,ordem,Itens de inspeção,Item de inspeção,testepadrão,MUITONível de inspeção,Unnamed: 11,Insira o resultado métodoC (dadosentrada)D (luta/decisão negativa),instrumento de mediçãogabarito,unidade,resoluçãoS/N,Unnamed: 16,ORGANIZAÇÃO,representanteP/N
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LGE,Empresa parceira,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,Nível de risco RoHSparade acordo comdivisão,NaN,NaN,RoHS (crítico),NaN,RoHS (crítico),RoHS (crítico),NaN,1EA,1EA,D,NaN,NaN,NaN,NaN,-,-
2,NaN,NaN,NaN,NaN,NaN,RoHS (Alto),NaN,RoHS (Alto),RoHS (Alto),NaN,1EA,1EA,D,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,RoHS (médio),NaN,RoHS (médio),RoHS (médio),NaN,1EA,1EA,D,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,dispositivo médicoAlvopapel,NaN,NaN,Inspeção Geral,0.5,dispositivo médico,Dispositivos Médicos,dispositivo médicoAlvopapelverificar,1EA,-,D,dispositivo médico LISTA DE BOM,NaN,NaN,NaN,NaN,ITEMparasem consideraritemadição gerenciamento...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,6.0,incorporação,Misturando,Não deve haver mistura de outros números/produ...,5EA,8EA,D,olho nu,NaN,NaN,NaN,NaN,NaN
296,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,7.0,Inspeção de óleo residual,Detecção de óleo,Não deve haver óleo na superfície da peça.,1EA,1EA,D,papel de óleo,NaN,NaN,NaN,NaN,NaN
297,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,8.0,Borda afiada,Borda afiada,Cumpra os padrões de julgamento da Sharp Edge.,1EA,1EA,D,Teste de tentáculos e testador de bordas afiadas,NaN,NaN,NaN,NaN,NaN
298,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,9.0,RoHS,RoHS,Deve atender aos padrões de inspeção de import...,1EA,1EA,D,Instrumento de medição XRF,NaN,NaN,NaN,NaN,NaN
299,NaN,NaN,NaN,NaN,NaN,"RoHS (seleção crítica, alta e média)",10.0,"RoHS (seleção crítica, alta e média)",RoHS (selecione Crítico ou Alto ou Médio),Os padrões devem ser atendidos na verificação ...,1EA,1EA,D,Dados de medição XRF do parceiro,NaN,NaN,NaN,NaN,NaN

In [53]:
# Carrega o arquivo Excel tratando células mescladas
f = pd.read_excel("2.Mechanical Sampling_v2 (P).xlsx", sheet_name=0, header=0)

In [54]:
import pandas as pd

# Carrega o arquivo Excel
f = pd.read_excel("2.Mechanical Sampling_v2 (P).xlsx")

# Exibe as linhas de 145 a 151 (lembrando que os índices começam em 0)
display(f.iloc[143:148])  # O último índice (152) não é incluído

,Unnamed: 0,Não,padrão número (Rev.)Data de revisão,Item,Alto riscoAlvoSe,G-ERPteste Tipo,ordem,Itens de inspeção,Item de inspeção,testepadrão,MUITONível de inspeção,Unnamed: 11,Insira o resultado métodoC (dadosentrada)D (luta/decisão negativa),instrumento de mediçãogabarito,unidade,resoluçãoS/N,Unnamed: 16,ORGANIZAÇÃO,representanteP/N
143,NaN,12.0,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,N,Inspeção Geral,1.0,aparência,Aparência,Satisfaça os critérios de aparência.,"C = 0, AQL = 2,5","C = 0, AQL = 1,5",D,olho nu,NaN,NaN,NaN,GLZ,MAP65186201_Jin-seon Lee_Excluir itens de dese...
144,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,2.0,estrutura,Estrutura,Combine o desenho.,2EA/LOTE,5EA/LOTE,D,"olho nu, desenho",NaN,NaN,NaN,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...
145,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,3.0,incorporação,Misturando,Não deve haver mistura de outros números/produ...,"C = 0, AQL = 2,5","C = 0, AQL = 1,5",D,"olho nu, desenho",NaN,NaN,NaN,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,4.0,Status da embalagem,Status da embalagem,Combine o desenho.,2EA/LOTE,5EA/LOTE,D,"Inspeção visual, desenho, fita métrica",NaN,NaN,NaN,NaN,NaN
147,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,5.0,RoHS,RoHS,Deve atender aos padrões de inspeção de import...,1EA,1EA,D,Instrumento de medição XRF,NaN,NaN,NaN,NaN,NaN

In [55]:
# Cria um novo DataFrame com as linhas 145 a 151
df_subset = f.iloc[145:152]  # Índices no Pandas começam em 0

# Exibe o novo DataFrame
display(df_subset)

,Unnamed: 0,Não,padrão número (Rev.)Data de revisão,Item,Alto riscoAlvoSe,G-ERPteste Tipo,ordem,Itens de inspeção,Item de inspeção,testepadrão,MUITONível de inspeção,Unnamed: 11,Insira o resultado métodoC (dadosentrada)D (luta/decisão negativa),instrumento de mediçãogabarito,unidade,resoluçãoS/N,Unnamed: 16,ORGANIZAÇÃO,representanteP/N
145,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,3.0,incorporação,Misturando,Não deve haver mistura de outros números/produ...,"C = 0, AQL = 2,5","C = 0, AQL = 1,5",D,"olho nu, desenho",NaN,NaN,NaN,NaN,NaN
146,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,4.0,Status da embalagem,Status da embalagem,Combine o desenho.,2EA/LOTE,5EA/LOTE,D,"Inspeção visual, desenho, fita métrica",NaN,NaN,NaN,NaN,NaN
147,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,5.0,RoHS,RoHS,Deve atender aos padrões de inspeção de import...,1EA,1EA,D,Instrumento de medição XRF,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,"RoHS (seleção crítica, alta e média)",6.0,"RoHS (seleção crítica, alta e média)",RoHS (selecione Crítico ou Alto ou Médio),Os padrões devem ser atendidos na verificação ...,1EA,1EA,D,Dados de medição XRF do parceiro,NaN,NaN,NaN,NaN,NaN
149,NaN,13.0,LG(53)-G7-2047 LG(51)-G7-2047 Linha de produto...,Pratos decorativos Deco,N,Inspeção Geral,1.0,aparência,Aparência,Satisfaça os critérios de aparência.,"C = 0, AQL = 2,5","C = 0, AQL = 1,5",D,olho nu,NaN,NaN,NaN,GLZ,MCR68446601_Jin-seon Lee_Delete itens de desen...
150,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,2.0,estrutura,Estrutura,Combine o desenho.,2EA/LOTE,5EA/LOTE,D,"olho nu, desenho",NaN,NaN,NaN,GMZ,MCR68427104_Jin-seon Lee_Delete itens de desen...
151,NaN,NaN,NaN,NaN,NaN,Inspeção Geral,3.0,tamanho,Dimensões,Esteja satisfeito com as especificações do des...,2EA/LOTE,5EA/LOTE,C,"Paquímetros Vernier, desenhos",milímetros,S,0.0,NaN,NaN

In [58]:
# Preenche células mescladas com os valores superiores
f.fillna(method='ffill', inplace=True)

# Exibir a coluna desejada com a linha específica
coluna_filtro = "padrão número (Rev.)Data de revisão"
filtro = f[f[coluna_desejada].astype(str).str.contains("LG\(53\)-G7-2050 LG\(51\)-G7-2050", na=False)]

# Lista de colunas adicionais que queremos exibir
colunas_desejadas = [
    "Item", "Alto riscoAlvoSe", "G-ERPteste", "Tipo", "ordem", "Itens de inspeção", 
    "Item de inspeção", "testepadrão", "MUITONível de inspeção", "Unnamed: 11", 
    "Insira o resultado métodoC (dadosentrada)D (luta/decisão negativa)", 
    "instrumento de mediçãogabarito", "unidade", "resoluçãoS/N", "Unnamed: 16", 
    "ORGANIZAÇÃO", "representanteP/N"
]

# Garantir que as colunas existem no DataFrame antes de selecionar
colunas_existentes = [col for col in colunas_desejadas if col in filtro.columns]

# Exibe apenas as colunas que existem no DataFrame
display(filtro[[coluna_filtro] + colunas_existentes])

C:\Users\noturno\AppData\Local\Temp\ipykernel_11516\990784885.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  f.fillna(method='ffill', inplace=True)

,padrão número (Rev.)Data de revisão,Item,ordem,Itens de inspeção,Item de inspeção,testepadrão,Unnamed: 11,Insira o resultado métodoC (dadosentrada)D (luta/decisão negativa),unidade,Unnamed: 16,ORGANIZAÇÃO,representanteP/N
143,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,1.0,aparência,Aparência,Satisfaça os critérios de aparência.,"C = 0, AQL = 1,5",D,Ah,0.0,GLZ,MAP65186201_Jin-seon Lee_Excluir itens de dese...
144,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,2.0,estrutura,Estrutura,Combine o desenho.,5EA/LOTE,D,Ah,0.0,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...
145,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,3.0,incorporação,Misturando,Não deve haver mistura de outros números/produ...,"C = 0, AQL = 1,5",D,Ah,0.0,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...
146,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,4.0,Status da embalagem,Status da embalagem,Combine o desenho.,5EA/LOTE,D,Ah,0.0,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...
147,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,5.0,RoHS,RoHS,Deve atender aos padrões de inspeção de import...,1EA,D,Ah,0.0,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...
148,LG(53)-G7-2050 LG(51)-G7-2050 Linha de produto...,Outros materiais subsidiários (produtos adquir...,6.0,"RoHS (seleção crítica, alta e média)",RoHS (selecione Crítico ou Alto ou Médio),Os padrões devem ser atendidos na verificação ...,1EA,D,Ah,0.0,GMZ,MEG61874103_Jin-seon Lee_Excluir itens de dese...